// Generated by scripts/embed-migrations.mjs from ../migrations — do not edit by hand.
// `pnpm db:generate` regenerates it after drizzle-kit adds a migration.
import type { MigrationMeta } from 'drizzle-orm/migrator';

/** The bundled SQL migrations, in order. Equivalent to drizzle's `readMigrationFiles()` on the `migrations/` folder. */
export const migrations: MigrationMeta[] = [
  // 0000_init
  {
    sql: [
      'CREATE TABLE "renkei_identity" (\n\t"sub" text PRIMARY KEY NOT NULL,\n\t"email" text,\n\t"email_verified" boolean,\n\t"display_name" text,\n\t"picture_url" text,\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL,\n\t"updated_at" timestamp with time zone DEFAULT now() NOT NULL\n);\n',
      '\nCREATE TABLE "renkei_line_account" (\n\t"identity_sub" text NOT NULL,\n\t"channel_id" text NOT NULL,\n\t"line_user_id" text NOT NULL,\n\t"kind" text NOT NULL,\n\t"friend" boolean,\n\t"friend_checked_at" timestamp with time zone,\n\t"raw_profile" jsonb,\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL,\n\t"updated_at" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT "renkei_line_account_channel_id_line_user_id_pk" PRIMARY KEY("channel_id","line_user_id")\n);\n',
      '\nCREATE TABLE "renkei_payload" (\n\t"model" text NOT NULL,\n\t"id" text NOT NULL,\n\t"payload" jsonb NOT NULL,\n\t"uid" text,\n\t"user_code" text,\n\t"grant_id" text,\n\t"expires_at" timestamp with time zone,\n\t"consumed_at" timestamp with time zone,\n\tCONSTRAINT "renkei_payload_model_id_pk" PRIMARY KEY("model","id")\n);\n',
      '\nALTER TABLE "renkei_line_account" ADD CONSTRAINT "renkei_line_account_identity_sub_renkei_identity_sub_fk" FOREIGN KEY ("identity_sub") REFERENCES "public"."renkei_identity"("sub") ON DELETE cascade ON UPDATE no action;',
      '\nCREATE INDEX "renkei_line_account_identity_idx" ON "renkei_line_account" USING btree ("identity_sub");',
      '\nCREATE INDEX "renkei_payload_uid_idx" ON "renkei_payload" USING btree ("model","uid");',
      '\nCREATE INDEX "renkei_payload_user_code_idx" ON "renkei_payload" USING btree ("model","user_code");',
      '\nCREATE INDEX "renkei_payload_grant_idx" ON "renkei_payload" USING btree ("model","grant_id");',
      '\nCREATE INDEX "renkei_payload_expires_idx" ON "renkei_payload" USING btree ("expires_at");',
    ],
    bps: true,
    folderMillis: 1787675806772,
    hash: '041176a7d46679c59e4946ef78ff84eb59bfafe774c4beb6494ab56e28f4b775',
  },
];
