// `renkei init`, `renkei add-channel` and `renkei add-client`. Pure functions
// over a working directory and an output sink so the tests can drive them
// without a shell.
//
// Two config shapes are supported and every command writes to exactly one of
// them: a renkei.yaml in the working directory if there is one, otherwise .env.
// `configTarget()` decides, once, per command.
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { configFromEnv, generateDevJwks, oidcClientSchema } from 'renkei-server';
import { parseEnv, readEnvFile, setEnvLine } from './env-file.js';
import {
  clientSecretVarName,
  configTarget,
  readDocument,
  secretVarName,
  upsertInSequence,
  writeDocument,
} from './yaml-file.js';
import { convertedYaml, templateEnv, templateYaml } from './yaml-init.js';

export const HELP = `renkei — self-hosted identity broker for LINE

usage: renkei                          start the server (renkei.yaml if there is one, else .env)
       renkei init [--yaml] [--issuer URL] [--db URL] [--print]
                                       write a ready-to-run config; you only paste the
                                       LINE channel ID and secret. --yaml writes a
                                       committable renkei.yaml + a .env of secrets
                                       (converting an existing .env if there is one)
       renkei add-channel <channel-id> [--region jp] [--miniapp] [--provider <name>]
                           [--secret <value>] [--secret-env <VAR>] [--liff-id <id>]
                           [--bot-prompt aggressive|normal|none] [--replace] [--print]
                                       add a LINE channel to renkei.yaml (secret by
                                       \${VAR} reference; the value goes to .env)
       renkei add-client <id> --redirect <url> [--preset authjs|supabase|public|next]
                           [--placeholder-email-domain <domain>] [--region jp]
                           [--replace] [--print]
                                       register an OIDC client (in renkei.yaml if there
                                       is one, else RENKEI_CLIENTS in .env) and print
                                       the config to paste into that app
       renkei --version

Config:       renkei.yaml when present (RENKEI_CONFIG overrides the path), else
              LINE_LOGIN_CHANNEL_ID / LINE_LOGIN_CHANNEL_SECRET and friends in .env
Docs:         https://github.com/AchrafReyani/renkei`;

const DEFAULT_ISSUER = 'http://localhost:3000';
const DEFAULT_DB = 'sqlite:./data/renkei.db';

/**
 * @typedef {{ cwd?: string, stdout?: (line: string) => void, now?: () => Date,
 *   jwks?: () => Promise<Array<Record<string, unknown>>> }} Io
 */

/**
 * Entry used by bin/renkei.js. Returns an exit code; never calls process.exit.
 * @param {string[]} argv @param {Io} [io]
 */
export async function run(argv, io = {}) {
  const out = io.stdout ?? ((line) => console.log(line));
  const [command, ...rest] = argv;
  try {
    if (command === 'init') return await init(rest, { ...io, stdout: out });
    if (command === 'add-channel') return await addChannel(rest, { ...io, stdout: out });
    if (command === 'add-client') return await addClient(rest, { ...io, stdout: out });
    out(HELP);
    return command === undefined ? 0 : 1;
  } catch (err) {
    out(`renkei ${command}: ${err instanceof Error ? err.message : String(err)}`);
    return 1;
  }
}

// ── init ────────────────────────────────────────────────────────────────────

/** @param {string[]} argv @param {Io & { stdout: (line: string) => void }} io */
export async function init(argv, io) {
  const { values } = parseArgs({
    args: argv,
    options: {
      issuer: { type: 'string', default: DEFAULT_ISSUER },
      db: { type: 'string', default: DEFAULT_DB },
      yaml: { type: 'boolean', default: false },
      print: { type: 'boolean', default: false },
    },
  });
  const issuer = normalizeIssuer(values.issuer);
  const envPath = resolve(io.cwd ?? process.cwd(), '.env');
  if (values.yaml) return await initYaml(values, { ...io, envPath, issuer });
  if (!values.print && existsSync(envPath)) {
    throw new Error(
      `${envPath} already exists — not overwriting a file that may hold secrets. ` +
        'Use `renkei add-client` to add apps to it, or `renkei init --print` to see what a fresh one looks like.',
    );
  }
  const date = (io.now ?? (() => new Date()))().toISOString().slice(0, 10);
  const jwks = await (io.jwks ?? generateJwks)();
  const text = [
    `# renkei — generated by \`renkei init\` on ${date}. This file holds secrets: keep it out of git.`,
    '#',
    '# 1. LINE Developers Console → your LINE Login channel → Basic settings → Channel ID / Channel secret:',
    'LINE_LOGIN_CHANNEL_ID=',
    'LINE_LOGIN_CHANNEL_SECRET=',
    `# 2. On the same channel, LINE Login tab → Callback URL: ${issuer}/line/callback`,
    `# 3. \`npx renkei\` and open ${issuer}/dev to log in with LINE.`,
    '# 4. `renkei add-client <id> --redirect <url> --preset authjs|supabase|public|next` registers your app.',
    '',
    '# Public URL of renkei (the OIDC issuer). No trailing slash.',
    `ISSUER=${issuer}`,
    "# Storage: 'sqlite:<file>' needs no database server (Node 22.13+); 'postgres://…' for multi-instance deploys.",
    `DATABASE_URL=${values.db}`,
    '# Generated secrets. Rotate by prepending a new value (cookie keys) / a new JWK (signing keys).',
    `RENKEI_COOKIE_KEYS=${randomBytes(32).toString('base64url')}`,
    `RENKEI_JWKS=${JSON.stringify(jwks)}`,
    '# Test page at /dev. Set to false (or remove) before going live.',
    'RENKEI_DEV=true',
    '',
    '# Optional — see https://github.com/AchrafReyani/renkei/blob/main/docs/reference/config.en.md',
    '# LINE_LOGIN_REGION=jp',
    '# RENKEI_BOT_PROMPT=aggressive',
    '# RENKEI_REQUEST_EMAIL=false',
    '# LINE_MESSAGING_CHANNEL_ID=',
    '# LINE_MESSAGING_CHANNEL_SECRET=',
    '# LINE_MESSAGING_CHANNEL_ACCESS_TOKEN=',
    '# RENKEI_ADMIN_TOKEN=',
    '',
  ].join('\n');

  if (values.print) {
    io.stdout(text);
    return 0;
  }
  writeFileSync(envPath, text);
  io.stdout(`Wrote ${envPath}`);
  io.stdout('');
  io.stdout('Next:');
  io.stdout('  1. Paste LINE_LOGIN_CHANNEL_ID and LINE_LOGIN_CHANNEL_SECRET into .env');
  io.stdout(`  2. Register ${issuer}/line/callback as a Callback URL on that channel`);
  io.stdout(`  3. npx renkei   →   ${issuer}/dev`);
  return 0;
}

async function generateJwks() {
  const [jwk] = await generateDevJwks();
  return [{ ...jwk, kid: `k${Date.now().toString(36)}` }];
}

/**
 * `renkei init --yaml`: a committable renkei.yaml plus the .env of secrets it
 * refers to. With a .env already there, the file is *converted* from it rather
 * than templated — the server's own `configFromEnv` builds the config, so the
 * YAML says exactly what those variables were already booting.
 *
 * @param {{ issuer: string, db: string, print: boolean }} values
 * @param {Io & { stdout: (line: string) => void, envPath: string, issuer: string }} io
 */
async function initYaml(values, io) {
  const cwd = io.cwd ?? process.cwd();
  const target = configTarget(cwd);
  if (!values.print && target.kind === 'yaml') {
    throw new Error(
      `${target.path} already exists — not overwriting it. ` +
        'Use `renkei add-channel` / `renkei add-client` to add to it.',
    );
  }
  const yamlPath = resolve(cwd, 'renkei.yaml');
  const date = (io.now ?? (() => new Date()))().toISOString().slice(0, 10);
  const existing = existsSync(io.envPath) ? parseEnv(readFileSync(io.envPath, 'utf8')) : undefined;

  if (existing?.LINE_LOGIN_CHANNEL_ID || existing?.RENKEI_CHANNELS) {
    const { config } = configFromEnv(existing, { hasDatabase: Boolean(existing.DATABASE_URL) });
    const { text, secrets } = convertedYaml(config, existing, date);
    if (values.print) {
      io.stdout(text);
      for (const [name, value] of Object.entries(secrets)) io.stdout(`${name}=${value}`);
      return 0;
    }
    writeFileSync(yamlPath, text);
    // Secrets that were buried inside RENKEI_CLIENTS / RENKEI_CHANNELS JSON have
    // no variable of their own yet; the file references one, so .env must define it.
    let envText = readFileSync(io.envPath, 'utf8');
    for (const [name, value] of Object.entries(secrets)) envText = setEnvLine(envText, name, value);
    if (Object.keys(secrets).length) writeFileSync(io.envPath, envText);

    io.stdout(`Wrote ${yamlPath}, converted from ${io.envPath}.`);
    io.stdout('');
    if (Object.keys(secrets).length) {
      io.stdout('Secrets that had no variable of their own (they were inside JSON) got one:');
      for (const name of Object.keys(secrets)) io.stdout(`  ${name}`);
      io.stdout('They are in .env now; renkei.yaml only references them.');
      io.stdout('');
    }
    io.stdout('renkei.yaml is now the whole configuration: the LINE_* / RENKEI_* variables it');
    io.stdout('supersedes are ignored from the next boot, and renkei names them when it starts.');
    io.stdout('Once it boots clean, the superseded lines can come out of .env.');
    return 0;
  }

  const jwks = await (io.jwks ?? generateJwks)();
  const cookieKeys = randomBytes(32).toString('base64url');
  const text = templateYaml({ issuer: io.issuer, db: values.db, date });
  if (values.print) {
    io.stdout(text);
    return 0;
  }
  if (existsSync(io.envPath)) {
    throw new Error(
      `${io.envPath} exists but configures no LINE channel — fill in LINE_LOGIN_CHANNEL_ID first ` +
        '(then `renkei init --yaml` converts it), or move it aside.',
    );
  }
  writeFileSync(yamlPath, text);
  writeFileSync(io.envPath, templateEnv({ date, cookieKeys, jwks: JSON.stringify(jwks) }));
  io.stdout(`Wrote ${yamlPath} (commit this) and ${io.envPath} (do not).`);
  io.stdout('');
  io.stdout('Next:');
  io.stdout('  1. Paste LINE_LOGIN_CHANNEL_ID and LINE_LOGIN_CHANNEL_SECRET into .env');
  io.stdout(`  2. Register ${io.issuer}/line/callback as a Callback URL on that channel`);
  io.stdout(`  3. npx renkei   →   ${io.issuer}/dev`);
  return 0;
}

// ── add-channel ─────────────────────────────────────────────────────────────

const BOT_PROMPTS = /** @type {const} */ (['aggressive', 'normal', 'none']);

/**
 * `renkei add-channel <channel-id>` — a second region, a MINI App stage, a
 * channel from another provider. YAML only: in .env the same thing is a JSON
 * blob in RENKEI_CHANNELS, which is what renkei.yaml exists to replace.
 *
 * The secret never lands in the YAML. `--secret <value>` writes the value to
 * .env under a derived name and the reference into the file; `--secret-env VAR`
 * only writes the reference, for a secret that reaches the process another way.
 *
 * @param {string[]} argv @param {Io & { stdout: (line: string) => void }} io
 */
export async function addChannel(argv, io) {
  const { values, positionals } = parseArgs({
    args: argv,
    allowPositionals: true,
    options: {
      region: { type: 'string' },
      miniapp: { type: 'boolean', default: false },
      provider: { type: 'string' },
      secret: { type: 'string' },
      'secret-env': { type: 'string' },
      'liff-id': { type: 'string', multiple: true, default: [] },
      'bot-prompt': { type: 'string' },
      replace: { type: 'boolean', default: false },
      print: { type: 'boolean', default: false },
    },
  });
  const channelId = positionals[0];
  if (!channelId) {
    throw new Error(
      'usage: renkei add-channel <channel-id> [--region tw] [--miniapp] [--secret …]',
    );
  }
  if (values.secret && values['secret-env']) {
    throw new Error('give --secret (the value) or --secret-env (the variable name), not both');
  }
  if (values['bot-prompt'] && !BOT_PROMPTS.includes(/** @type {any} */ (values['bot-prompt']))) {
    throw new Error(`--bot-prompt must be one of ${BOT_PROMPTS.join(', ')}`);
  }

  const cwd = io.cwd ?? process.cwd();
  const target = configTarget(cwd);
  if (target.kind !== 'yaml') {
    throw new Error(
      'no renkei.yaml here — `renkei add-channel` writes to it. Run `renkei init --yaml` first ' +
        '(it converts an existing .env), or add the channel to RENKEI_CHANNELS by hand.',
    );
  }

  // A MINI App has one channel per stage, so its variable is named after the
  // channel; a Login channel gets one per region, which is how it is addressed.
  const region = values.region ?? 'jp';
  const secretVar = values['secret-env'] ?? secretVarName(region, values.miniapp, channelId);

  /** @type {Record<string, unknown>} */
  const entry = { id: channelId };
  if (values.miniapp) entry.kind = 'miniapp';
  entry.region = region;
  if (values.provider) entry.provider = values.provider;
  entry.secret = '${' + secretVar + '}';
  if (values['bot-prompt']) entry.bot_prompt = values['bot-prompt'];
  if (values['liff-id'].length) entry.liff_ids = values['liff-id'];

  const doc = readDocument(target.path);
  const result = upsertInSequence(
    doc,
    'channels',
    entry,
    (c) => String(c?.id ?? c?.channel_id ?? c?.channelId) === channelId,
    values.replace,
  );
  if (result === 'exists') {
    throw new Error(
      `channel "${channelId}" is already in ${target.path} — pass --replace to overwrite it.`,
    );
  }

  const envPath = resolve(cwd, '.env');
  if (values.print) {
    io.stdout(doc.toString({ lineWidth: 0 }));
  } else {
    writeDocument(target.path, doc);
    if (values.secret) {
      const text = existsSync(envPath) ? readFileSync(envPath, 'utf8') : '';
      writeFileSync(envPath, setEnvLine(text, secretVar, values.secret));
    }
    io.stdout(
      `${result === 'replaced' ? 'Replaced' : 'Added'} channel ${channelId} (${
        values.miniapp ? 'MINI App' : 'LINE Login'
      }, region ${region}) in ${target.path}.`,
    );
  }
  io.stdout('');
  if (values.secret) {
    io.stdout(`Its secret is in .env as ${secretVar}; the file only references it.`);
  } else if (values['secret-env']) {
    io.stdout(`Set ${secretVar} in the environment renkei runs in — the file only references it.`);
  } else {
    io.stdout(`Add the channel secret to .env:   ${secretVar}=<Channel secret>`);
  }
  if (!values.miniapp) {
    io.stdout('');
    io.stdout('On that channel in the LINE Developers Console:');
    io.stdout('  LINE Login tab → Callback URL: <your issuer>/line/callback');
    io.stdout(`  A login reaches it with ?line_region=${region} (or a client pinned to it).`);
  }
  io.stdout('Restart renkei to pick it up.');
  return 0;
}

// ── add-client ──────────────────────────────────────────────────────────────

const PRESETS = /** @type {const} */ (['authjs', 'supabase', 'public', 'next']);

/** @param {string[]} argv @param {Io & { stdout: (line: string) => void }} io */
export async function addClient(argv, io) {
  const { values, positionals } = parseArgs({
    args: argv,
    allowPositionals: true,
    options: {
      redirect: { type: 'string', multiple: true, default: [] },
      preset: { type: 'string' },
      'placeholder-email-domain': { type: 'string' },
      region: { type: 'string' },
      issuer: { type: 'string' },
      replace: { type: 'boolean', default: false },
      print: { type: 'boolean', default: false },
    },
  });
  const clientId = positionals[0];
  if (!clientId) throw new Error('usage: renkei add-client <id> --redirect <url> [--preset …]');
  const preset = values.preset;
  if (preset !== undefined && !PRESETS.includes(/** @type {any} */ (preset))) {
    throw new Error(`--preset must be one of ${PRESETS.join(', ')}`);
  }
  if (values.redirect.length === 0) {
    throw new Error(
      `--redirect is required. ${
        preset === 'supabase'
          ? 'Supabase: https://<project-ref>.supabase.co/auth/v1/callback (local CLI: http://127.0.0.1:54321/auth/v1/callback)'
          : preset === 'authjs'
            ? 'Auth.js: <app origin>/api/auth/callback/renkei'
            : preset === 'next'
              ? 'Next.js (renkei-next): <app origin>/api/renkei/callback'
              : 'Example: https://app.example.com/callback'
      }`,
    );
  }

  const cwd = io.cwd ?? process.cwd();
  const target = configTarget(cwd);
  const envPath = resolve(cwd, '.env');
  const env = readEnvFile(envPath);
  if (!values.print && !existsSync(target.path)) {
    throw new Error(`${target.path} not found — run \`renkei init\` first, or use --print.`);
  }
  const issuer = normalizeIssuer(
    values.issuer ??
      (target.kind === 'yaml' ? issuerFromYaml(target.path, env) : undefined) ??
      env.ISSUER ??
      DEFAULT_ISSUER,
  );

  /** @type {Record<string, unknown>} */
  const client = { clientId, redirectUris: values.redirect };
  if (preset === 'public') {
    client.tokenEndpointAuthMethod = 'none';
  } else {
    client.clientSecret = randomBytes(24).toString('base64url');
  }
  const placeholderDomain =
    values['placeholder-email-domain'] ??
    (preset === 'supabase' ? `line-users.${new URL(issuer).hostname}` : undefined);
  if (placeholderDomain) client.placeholderEmailDomain = placeholderDomain;
  if (values.region) client.lineRegion = values.region;
  const parsed = oidcClientSchema.parse(client);

  if (target.kind === 'yaml') {
    addClientToYaml(target.path, envPath, parsed, values, io);
  } else {
    addClientToEnv(envPath, env, parsed, values, io);
  }
  io.stdout('');
  for (const l of snippet(preset, parsed, issuer)) io.stdout(l);
  return 0;
}

/** RENKEI_CLIENTS in .env: the whole list is one JSON value, rewritten each time. */
function addClientToEnv(envPath, env, client, values, io) {
  const existing = parseClients(env.RENKEI_CLIENTS);
  const at = existing.findIndex((c) => c && c.clientId === client.clientId);
  if (at >= 0 && !values.replace) {
    throw new Error(
      `client "${client.clientId}" is already in RENKEI_CLIENTS — pass --replace to overwrite it.`,
    );
  }
  const line = JSON.stringify(at >= 0 ? existing.with(at, client) : [...existing, client]);
  if (values.print) {
    io.stdout(`RENKEI_CLIENTS=${line}`);
    return;
  }
  writeFileSync(envPath, setEnvLine(readFileSync(envPath, 'utf8'), 'RENKEI_CLIENTS', line));
  io.stdout(`Added client "${client.clientId}" to ${envPath} (restart renkei to pick it up).`);
}

/**
 * The `clients:` list in renkei.yaml. As with channels, the generated secret
 * goes to .env and the file gets the `${VAR}` reference — that is what keeps
 * renkei.yaml committable.
 */
function addClientToYaml(yamlPath, envPath, client, values, io) {
  const secretVar = client.clientSecret ? clientSecretVarName(client.clientId) : undefined;
  /** @type {Record<string, unknown>} */
  const entry = { client_id: client.clientId };
  if (secretVar) entry.client_secret = '${' + secretVar + '}';
  entry.redirect_uris = client.redirectUris;
  if (client.tokenEndpointAuthMethod !== 'client_secret_basic') {
    entry.token_endpoint_auth_method = client.tokenEndpointAuthMethod;
  }
  if (client.lineRegion) entry.line_region = client.lineRegion;
  if (client.placeholderEmailDomain) entry.placeholder_email_domain = client.placeholderEmailDomain;

  const doc = readDocument(yamlPath);
  const result = upsertInSequence(
    doc,
    'clients',
    entry,
    (c) => (c?.client_id ?? c?.clientId) === client.clientId,
    values.replace,
  );
  if (result === 'exists') {
    throw new Error(
      `client "${client.clientId}" is already in ${yamlPath} — pass --replace to overwrite it.`,
    );
  }
  if (values.print) {
    io.stdout(doc.toString({ lineWidth: 0 }));
    return;
  }
  writeDocument(yamlPath, doc);
  if (secretVar) {
    const text = existsSync(envPath) ? readFileSync(envPath, 'utf8') : '';
    writeFileSync(envPath, setEnvLine(text, secretVar, client.clientSecret));
  }
  io.stdout(
    `${result === 'replaced' ? 'Replaced' : 'Added'} client "${client.clientId}" in ${yamlPath}` +
      `${secretVar ? `, its secret in ${envPath} as ${secretVar}` : ''} (restart renkei to pick it up).`,
  );
}

/** The issuer a renkei.yaml declares, so the printed snippet points at the right renkei. */
function issuerFromYaml(path, env) {
  const value = readDocument(path).get('issuer');
  if (typeof value !== 'string') return undefined;
  // The file may name it by reference; the .env next to it is where that lives.
  return value.replace(
    /\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\}/g,
    (_m, name, fallback) => env[name] ?? fallback ?? '',
  );
}

/** @param {string | undefined} raw */
function parseClients(raw) {
  if (!raw?.trim()) return [];
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error('RENKEI_CLIENTS in .env is not valid JSON — fix or remove it first.');
  }
  if (!Array.isArray(parsed)) throw new Error('RENKEI_CLIENTS in .env must be a JSON array.');
  return parsed;
}

/**
 * What to paste on the application side, with the secret filled in.
 * @param {string | undefined} preset @param {any} c @param {string} issuer
 */
export function snippet(preset, c, issuer) {
  if (preset === 'supabase') {
    return [
      'Supabase → Authentication → Providers → Keycloak (renkei answers on Keycloak paths):',
      `  Client ID      ${c.clientId}`,
      `  Client Secret  ${c.clientSecret}`,
      `  Realm URL      ${issuer}`,
      '',
      'Local CLI (supabase/config.toml):',
      '  [auth.external.keycloak]',
      '  enabled = true',
      `  client_id = "${c.clientId}"`,
      `  secret = "${c.clientSecret}"`,
      `  url = "${issuer}"`,
      '',
      `Users without a LINE email get <sub>@${c.placeholderEmailDomain} (email_placeholder: true) —`,
      'read docs/tutorials/supabase.en.md §4 before going live.',
    ];
  }
  if (preset === 'next') {
    return [
      'renkei-next — .env.local of the Next.js app:',
      `  RENKEI_ISSUER=${issuer}`,
      `  RENKEI_CLIENT_ID=${c.clientId}`,
      `  RENKEI_CLIENT_SECRET=${c.clientSecret}`,
      `  RENKEI_NEXT_SECRET=${randomBytes(32).toString('base64url')}`,
      '',
      'renkei.ts:',
      "  import { createRenkeiAuth } from 'renkei-next';",
      '  export const renkei = createRenkeiAuth({',
      '    issuer: process.env.RENKEI_ISSUER!, clientId: process.env.RENKEI_CLIENT_ID!,',
      '    clientSecret: process.env.RENKEI_CLIENT_SECRET, secret: process.env.RENKEI_NEXT_SECRET!,',
      '  });',
      '',
      'app/api/renkei/[...renkei]/route.ts:   export const { GET, POST } = renkei.handlers;',
      "proxy.ts (middleware.ts on Next ≤ 15): export default renkei.proxy({ protect: ['/account'] });",
      "any page:                              import { LineLoginButton } from 'renkei-next/button';",
    ];
  }
  if (preset === 'authjs') {
    return [
      'Auth.js (next-auth v5) — .env.local of the Next.js app:',
      `  RENKEI_ISSUER=${issuer}`,
      `  RENKEI_CLIENT_ID=${c.clientId}`,
      `  RENKEI_CLIENT_SECRET=${c.clientSecret}`,
      '',
      'auth.ts:',
      '  providers: [{',
      "    id: 'renkei', name: 'LINE', type: 'oidc',",
      '    issuer: process.env.RENKEI_ISSUER,',
      '    clientId: process.env.RENKEI_CLIENT_ID,',
      '    clientSecret: process.env.RENKEI_CLIENT_SECRET,',
      "    authorization: { params: { scope: 'openid profile email line' } },",
      '  }]',
    ];
  }
  const lines = [
    'OIDC client settings:',
    `  issuer / discovery  ${issuer}/.well-known/openid-configuration`,
    `  client_id           ${c.clientId}`,
  ];
  if (c.clientSecret) lines.push(`  client_secret       ${c.clientSecret}`);
  else lines.push('  public client       no secret; PKCE (S256) is required');
  lines.push(`  redirect_uri        ${c.redirectUris.join(', ')}`);
  lines.push('  scope               openid profile email line');
  lines.push('');
  lines.push('renkei-client (npm i renkei-client) — browsers / Node / Workers:');
  lines.push("  import { createRenkeiClient } from 'renkei-client';");
  lines.push(
    `  const renkei = createRenkeiClient({ issuer: '${issuer}', clientId: '${c.clientId}' });`,
  );
  lines.push(
    `  location.href = renkei.loginUrl({ redirectUri: '${c.redirectUris[0]}', state, nonce${
      c.clientSecret ? '' : ', codeChallenge'
    } });`,
  );
  return lines;
}

/** @param {string} url */
function normalizeIssuer(url) {
  let u;
  try {
    u = new URL(url);
  } catch {
    throw new Error(`issuer must be an absolute URL, got "${url}"`);
  }
  return u.toString().replace(/\/$/, '');
}
