// `renkei init` and `renkei add-client`. Pure functions over a working
// directory and an output sink so the tests can drive them without a shell.
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { generateDevJwks, oidcClientSchema } from 'renkei-server';
import { readEnvFile, setEnvLine } from './env-file.js';

export const HELP = `renkei — self-hosted identity broker for LINE

usage: renkei                          start the server (reads .env / environment)
       renkei init [--issuer URL] [--db URL] [--print]
                                       write a ready-to-run .env (keys, SQLite storage);
                                       you only paste the LINE channel ID and secret
       renkei add-client <id> --redirect <url> [--preset authjs|supabase|public]
                           [--placeholder-email-domain <domain>] [--region jp]
                           [--replace] [--print]
                                       register an OIDC client in RENKEI_CLIENTS and
                                       print the config to paste into that app
       renkei --version

Required env: LINE_LOGIN_CHANNEL_ID, LINE_LOGIN_CHANNEL_SECRET
Recommended:  ISSUER, DATABASE_URL, RENKEI_COOKIE_KEYS, RENKEI_JWKS, RENKEI_CLIENTS
Docs:         https://github.com/AchrafReyani/renkei`;

const DEFAULT_ISSUER = 'http://localhost:3000';
const DEFAULT_DB = 'sqlite:./data/renkei.db';

/**
 * @typedef {{ cwd?: string, stdout?: (line: string) => void, now?: () => Date,
 *   jwks?: () => Promise<Array<Record<string, unknown>>> }} Io
 */

/**
 * Entry used by bin/renkei.js. Returns an exit code; never calls process.exit.
 * @param {string[]} argv @param {Io} [io]
 */
export async function run(argv, io = {}) {
  const out = io.stdout ?? ((line) => console.log(line));
  const [command, ...rest] = argv;
  try {
    if (command === 'init') return await init(rest, { ...io, stdout: out });
    if (command === 'add-client') return await addClient(rest, { ...io, stdout: out });
    out(HELP);
    return command === undefined ? 0 : 1;
  } catch (err) {
    out(`renkei ${command}: ${err instanceof Error ? err.message : String(err)}`);
    return 1;
  }
}

// ── init ────────────────────────────────────────────────────────────────────

/** @param {string[]} argv @param {Io & { stdout: (line: string) => void }} io */
export async function init(argv, io) {
  const { values } = parseArgs({
    args: argv,
    options: {
      issuer: { type: 'string', default: DEFAULT_ISSUER },
      db: { type: 'string', default: DEFAULT_DB },
      print: { type: 'boolean', default: false },
    },
  });
  const issuer = normalizeIssuer(values.issuer);
  const envPath = resolve(io.cwd ?? process.cwd(), '.env');
  if (!values.print && existsSync(envPath)) {
    throw new Error(
      `${envPath} already exists — not overwriting a file that may hold secrets. ` +
        'Use `renkei add-client` to add apps to it, or `renkei init --print` to see what a fresh one looks like.',
    );
  }
  const date = (io.now ?? (() => new Date()))().toISOString().slice(0, 10);
  const jwks = await (io.jwks ?? generateJwks)();
  const text = [
    `# renkei — generated by \`renkei init\` on ${date}. This file holds secrets: keep it out of git.`,
    '#',
    '# 1. LINE Developers Console → your LINE Login channel → Basic settings → Channel ID / Channel secret:',
    'LINE_LOGIN_CHANNEL_ID=',
    'LINE_LOGIN_CHANNEL_SECRET=',
    `# 2. On the same channel, LINE Login tab → Callback URL: ${issuer}/line/callback`,
    `# 3. \`npx renkei\` and open ${issuer}/dev to log in with LINE.`,
    '# 4. `renkei add-client <id> --redirect <url> --preset authjs|supabase|public` registers your app.',
    '',
    '# Public URL of renkei (the OIDC issuer). No trailing slash.',
    `ISSUER=${issuer}`,
    "# Storage: 'sqlite:<file>' needs no database server (Node 22.13+); 'postgres://…' for multi-instance deploys.",
    `DATABASE_URL=${values.db}`,
    '# Generated secrets. Rotate by prepending a new value (cookie keys) / a new JWK (signing keys).',
    `RENKEI_COOKIE_KEYS=${randomBytes(32).toString('base64url')}`,
    `RENKEI_JWKS=${JSON.stringify(jwks)}`,
    '# Test page at /dev. Set to false (or remove) before going live.',
    'RENKEI_DEV=true',
    '',
    '# Optional — see https://github.com/AchrafReyani/renkei/blob/main/docs/reference/config.en.md',
    '# LINE_LOGIN_REGION=jp',
    '# RENKEI_BOT_PROMPT=aggressive',
    '# RENKEI_REQUEST_EMAIL=false',
    '# LINE_MESSAGING_CHANNEL_ID=',
    '# LINE_MESSAGING_CHANNEL_SECRET=',
    '# LINE_MESSAGING_CHANNEL_ACCESS_TOKEN=',
    '# RENKEI_ADMIN_TOKEN=',
    '',
  ].join('\n');

  if (values.print) {
    io.stdout(text);
    return 0;
  }
  writeFileSync(envPath, text);
  io.stdout(`Wrote ${envPath}`);
  io.stdout('');
  io.stdout('Next:');
  io.stdout('  1. Paste LINE_LOGIN_CHANNEL_ID and LINE_LOGIN_CHANNEL_SECRET into .env');
  io.stdout(`  2. Register ${issuer}/line/callback as a Callback URL on that channel`);
  io.stdout(`  3. npx renkei   →   ${issuer}/dev`);
  return 0;
}

async function generateJwks() {
  const [jwk] = await generateDevJwks();
  return [{ ...jwk, kid: `k${Date.now().toString(36)}` }];
}

// ── add-client ──────────────────────────────────────────────────────────────

const PRESETS = /** @type {const} */ (['authjs', 'supabase', 'public']);

/** @param {string[]} argv @param {Io & { stdout: (line: string) => void }} io */
export async function addClient(argv, io) {
  const { values, positionals } = parseArgs({
    args: argv,
    allowPositionals: true,
    options: {
      redirect: { type: 'string', multiple: true, default: [] },
      preset: { type: 'string' },
      'placeholder-email-domain': { type: 'string' },
      region: { type: 'string' },
      issuer: { type: 'string' },
      replace: { type: 'boolean', default: false },
      print: { type: 'boolean', default: false },
    },
  });
  const clientId = positionals[0];
  if (!clientId) throw new Error('usage: renkei add-client <id> --redirect <url> [--preset …]');
  const preset = values.preset;
  if (preset !== undefined && !PRESETS.includes(/** @type {any} */ (preset))) {
    throw new Error(`--preset must be one of ${PRESETS.join(', ')}`);
  }
  if (values.redirect.length === 0) {
    throw new Error(
      `--redirect is required. ${
        preset === 'supabase'
          ? 'Supabase: https://<project-ref>.supabase.co/auth/v1/callback (local CLI: http://127.0.0.1:54321/auth/v1/callback)'
          : preset === 'authjs'
            ? 'Auth.js: <app origin>/api/auth/callback/renkei'
            : 'Example: https://app.example.com/callback'
      }`,
    );
  }

  const cwd = io.cwd ?? process.cwd();
  const envPath = resolve(cwd, '.env');
  const env = readEnvFile(envPath);
  if (!values.print && !existsSync(envPath)) {
    throw new Error(`${envPath} not found — run \`renkei init\` first, or use --print.`);
  }
  const issuer = normalizeIssuer(values.issuer ?? env.ISSUER ?? DEFAULT_ISSUER);

  /** @type {Record<string, unknown>} */
  const client = { clientId, redirectUris: values.redirect };
  if (preset === 'public') {
    client.tokenEndpointAuthMethod = 'none';
  } else {
    client.clientSecret = randomBytes(24).toString('base64url');
  }
  const placeholderDomain =
    values['placeholder-email-domain'] ??
    (preset === 'supabase' ? `line-users.${new URL(issuer).hostname}` : undefined);
  if (placeholderDomain) client.placeholderEmailDomain = placeholderDomain;
  if (values.region) client.lineRegion = values.region;
  const parsed = oidcClientSchema.parse(client);

  const existing = parseClients(env.RENKEI_CLIENTS);
  const at = existing.findIndex((c) => c && c.clientId === clientId);
  if (at >= 0 && !values.replace) {
    throw new Error(
      `client "${clientId}" is already in RENKEI_CLIENTS — pass --replace to overwrite it.`,
    );
  }
  const clients = at >= 0 ? existing.with(at, parsed) : [...existing, parsed];
  const line = JSON.stringify(clients);

  if (values.print) {
    io.stdout(`RENKEI_CLIENTS=${line}`);
  } else {
    writeFileSync(envPath, setEnvLine(readFileSync(envPath, 'utf8'), 'RENKEI_CLIENTS', line));
    io.stdout(`Added client "${clientId}" to ${envPath} (restart renkei to pick it up).`);
  }
  io.stdout('');
  for (const l of snippet(preset, parsed, issuer)) io.stdout(l);
  return 0;
}

/** @param {string | undefined} raw */
function parseClients(raw) {
  if (!raw?.trim()) return [];
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error('RENKEI_CLIENTS in .env is not valid JSON — fix or remove it first.');
  }
  if (!Array.isArray(parsed)) throw new Error('RENKEI_CLIENTS in .env must be a JSON array.');
  return parsed;
}

/**
 * What to paste on the application side, with the secret filled in.
 * @param {string | undefined} preset @param {any} c @param {string} issuer
 */
export function snippet(preset, c, issuer) {
  if (preset === 'supabase') {
    return [
      'Supabase → Authentication → Providers → Keycloak (renkei answers on Keycloak paths):',
      `  Client ID      ${c.clientId}`,
      `  Client Secret  ${c.clientSecret}`,
      `  Realm URL      ${issuer}`,
      '',
      'Local CLI (supabase/config.toml):',
      '  [auth.external.keycloak]',
      '  enabled = true',
      `  client_id = "${c.clientId}"`,
      `  secret = "${c.clientSecret}"`,
      `  url = "${issuer}"`,
      '',
      `Users without a LINE email get <sub>@${c.placeholderEmailDomain} (email_placeholder: true) —`,
      'read docs/tutorials/supabase.en.md §4 before going live.',
    ];
  }
  if (preset === 'authjs') {
    return [
      'Auth.js (next-auth v5) — .env.local of the Next.js app:',
      `  RENKEI_ISSUER=${issuer}`,
      `  RENKEI_CLIENT_ID=${c.clientId}`,
      `  RENKEI_CLIENT_SECRET=${c.clientSecret}`,
      '',
      'auth.ts:',
      '  providers: [{',
      "    id: 'renkei', name: 'LINE', type: 'oidc',",
      '    issuer: process.env.RENKEI_ISSUER,',
      '    clientId: process.env.RENKEI_CLIENT_ID,',
      '    clientSecret: process.env.RENKEI_CLIENT_SECRET,',
      "    authorization: { params: { scope: 'openid profile email line' } },",
      '  }]',
    ];
  }
  const lines = [
    'OIDC client settings:',
    `  issuer / discovery  ${issuer}/.well-known/openid-configuration`,
    `  client_id           ${c.clientId}`,
  ];
  if (c.clientSecret) lines.push(`  client_secret       ${c.clientSecret}`);
  else lines.push('  public client       no secret; PKCE (S256) is required');
  lines.push(`  redirect_uri        ${c.redirectUris.join(', ')}`);
  lines.push('  scope               openid profile email line');
  return lines;
}

/** @param {string} url */
function normalizeIssuer(url) {
  let u;
  try {
    u = new URL(url);
  } catch {
    throw new Error(`issuer must be an absolute URL, got "${url}"`);
  }
  return u.toString().replace(/\/$/, '');
}
