// Building a renkei.yaml: the template `renkei init --yaml` writes in an empty
// directory, and the conversion it writes when there is already a .env to read.
//
// Both produce the same shape: a committable file whose every secret is a
// `${VAR}` reference, next to a .env that holds the values. No secret is ever
// written into the YAML — `convertedYaml` hands back the ones it had to mint a
// variable for, and the caller puts those in .env.
import { clientSecretVarName, quoteReferences, secretVarName } from './yaml-file.js';

/**
 * The starting file for a directory with nothing in it. Hand-written rather
 * than serialized, because the comments are most of the value.
 * @param {{ issuer: string, db: string, date: string }} o
 */
export function templateYaml({ issuer, db, date }) {
  return `# renkei — generated by \`renkei init --yaml\` on ${date}.
#
# Safe to commit: every secret here is a \${VAR} reference, read from the
# environment (from .env in development). The values live in .env — keep that
# one out of git.
#
# 1. LINE Developers Console → your LINE Login channel → Basic settings:
#    put the Channel ID and Channel secret in .env.
# 2. On the same channel, LINE Login tab → Callback URL: ${issuer}/line/callback
# 3. \`npx renkei\` and open ${issuer}/dev to log in with LINE.
# 4. \`renkei add-client <id> --redirect <url>\`  registers an app  (appends to clients:)
#    \`renkei add-channel <id> --region tw\`      adds a channel    (appends to channels:)
#
# Every field: https://github.com/AchrafReyani/renkei/blob/main/docs/reference/config.en.md
# A channel can also carry  bot_prompt: normal|none,  request_email: true
# (once LINE has approved the channel for email),  liff_ids: [...],  provider:.

# Public URL of renkei (the OIDC issuer). No trailing slash.
issuer: ${issuer}
# 'sqlite:<file>' needs no database server (Node 22.13+); 'postgres://…' for multi-instance deploys.
storage: ${db}
# Test page at /dev. Remove (or set to false) before going live.
dev: true

# Generated at init and stored in .env. Rotate by prepending a new value
# (cookie keys) or a new JWK (signing keys) there.
cookie_keys: "\${RENKEI_COOKIE_KEYS}"
jwks: "\${RENKEI_JWKS}"

# LINE channels. \`renkei add-channel\` appends here.
channels:
  - id: "\${LINE_LOGIN_CHANNEL_ID}"
    region: jp
    secret: "\${LINE_LOGIN_CHANNEL_SECRET}"
    bot_prompt: aggressive

# Downstream OIDC clients. \`renkei add-client\` appends here.
clients: []
`;
}

/**
 * The .env that goes next to the template: the values its ${VAR}s refer to.
 * @param {{ date: string, cookieKeys: string, jwks: string }} o
 */
export function templateEnv({ date, cookieKeys, jwks }) {
  return [
    `# renkei — secrets for renkei.yaml, generated on ${date}. Keep this file out of git.`,
    '# LINE Developers Console → your LINE Login channel → Basic settings:',
    'LINE_LOGIN_CHANNEL_ID=',
    'LINE_LOGIN_CHANNEL_SECRET=',
    '',
    '# Generated. Losing these invalidates every issued token and session.',
    `RENKEI_COOKIE_KEYS=${cookieKeys}`,
    `RENKEI_JWKS=${jwks}`,
    '',
  ].join('\n');
}

/**
 * An existing .env rendered as renkei.yaml. The config is built by the server's
 * own `configFromEnv`, so the file says exactly what those variables were
 * already booting — then every value is written back as a `${VAR}` reference.
 *
 * A secret that came from a variable of its own keeps that variable's name. One
 * that was buried inside a JSON blob (`RENKEI_CHANNELS`, `RENKEI_CLIENTS`, the
 * comma-paired MINI App lists) has no name yet, so it gets one, and comes back
 * in `secrets` for the caller to append to .env. Nothing secret reaches the YAML.
 *
 * @param {import('renkei-server').RenkeiConfigInput} config
 * @param {Record<string, string>} env  the .env as read from disk
 * @param {string} date
 * @returns {{ text: string, secrets: Record<string, string> }}
 */
export function convertedYaml(config, env, date) {
  /** @type {Record<string, string>} */
  const secrets = {};
  const ref = referencer(env);
  /** Reference `value`, minting `fallbackVar` for it when no variable holds it. */
  const secret = (value, fallbackVar) => {
    if (!value) return value;
    const existing = ref(value);
    if (existing !== value) return existing;
    secrets[fallbackVar] = value;
    return `\${${fallbackVar}}`;
  };

  /** @type {Record<string, unknown>} */
  const out = {};
  out.issuer = ref(config.issuer);
  if (env.DATABASE_URL) out.storage = ref(env.DATABASE_URL);
  if (config.dev) out.dev = true;
  if (env.LIFF_ID) out.liff_id = ref(env.LIFF_ID);
  if (env.RENKEI_LOG_FORMAT === 'json') out.log_format = 'json';

  out.cookie_keys = secret((config.cookieKeys ?? []).join(','), 'RENKEI_COOKIE_KEYS');
  if (config.jwks) out.jwks = secret(JSON.stringify(config.jwks), 'RENKEI_JWKS');

  out.channels = (config.channels ?? []).map((c) => {
    const miniapp = c.kind === 'miniapp';
    /** @type {Record<string, unknown>} */
    const channel = { id: ref(c.channelId) };
    if (miniapp) channel.kind = 'miniapp';
    if (c.region) channel.region = c.region;
    if (c.provider) channel.provider = c.provider;
    channel.secret = secret(c.channelSecret, secretVarName(c.region ?? 'jp', miniapp, c.channelId));
    if (c.botPrompt && c.botPrompt !== 'aggressive') channel.bot_prompt = c.botPrompt;
    if (c.requestEmail) channel.request_email = true;
    if (c.liffIds?.length) channel.liff_ids = c.liffIds;
    return channel;
  });

  const messaging = (config.messagingChannels ?? []).map((m, i) => {
    const suffix = i === 0 ? '' : `_${i + 1}`;
    /** @type {Record<string, unknown>} */
    const entry = {};
    if (m.channelId) entry.channel_id = ref(m.channelId);
    if (m.region) entry.region = m.region;
    entry.channel_secret = secret(m.channelSecret, `LINE_MESSAGING_CHANNEL_SECRET${suffix}`);
    if (m.channelAccessToken) {
      entry.channel_access_token = secret(
        m.channelAccessToken,
        `LINE_MESSAGING_CHANNEL_ACCESS_TOKEN${suffix}`,
      );
    }
    if (m.accountLinkForwardUrl) entry.account_link_forward_url = ref(m.accountLinkForwardUrl);
    if (m.accountLinkForwardSecret) {
      entry.account_link_forward_secret = secret(
        m.accountLinkForwardSecret,
        `LINE_ACCOUNTLINK_FORWARD_SECRET${suffix}`,
      );
    }
    return entry;
  });
  if (messaging.length === 1) out.messaging = messaging[0];
  else if (messaging.length > 1) out.messaging_channels = messaging;

  if (config.corsOrigins?.length) out.cors_origins = config.corsOrigins;
  if (config.sessionCookie) {
    /** @type {Record<string, unknown>} */
    const session = { enabled: true };
    if (config.sessionCookie.returnUrls?.length) {
      session.return_urls = config.sessionCookie.returnUrls;
    }
    out.session_cookie = session;
  }
  if (config.adminToken) out.admin_token = secret(config.adminToken, 'RENKEI_ADMIN_TOKEN');

  // The /dev clients are added at boot from `dev: true`; writing them into the
  // file would freeze the issuer they point at into it.
  out.clients = (config.clients ?? [])
    .filter((c) => !c.clientId.startsWith('renkei-dev'))
    .map((c) => {
      /** @type {Record<string, unknown>} */
      const client = { client_id: c.clientId };
      if (c.clientSecret) {
        client.client_secret = secret(c.clientSecret, clientSecretVarName(c.clientId));
      }
      client.redirect_uris = c.redirectUris;
      if (c.tokenEndpointAuthMethod && c.tokenEndpointAuthMethod !== 'client_secret_basic') {
        client.token_endpoint_auth_method = c.tokenEndpointAuthMethod;
      }
      if (c.lineRegion) client.line_region = c.lineRegion;
      if (c.placeholderEmailDomain) client.placeholder_email_domain = c.placeholderEmailDomain;
      return client;
    });

  const header = `# renkei — converted from .env by \`renkei init --yaml\` on ${date}.
#
# Safe to commit: every secret is a \${VAR} reference and the values stay in
# .env. This file is now the whole configuration — renkei ignores the
# LINE_* / RENKEI_* variables it supersedes and says so at boot. The ones it
# still reads are the \${VAR}s below, plus PORT and DATABASE_URL.
#
# Reference: https://github.com/AchrafReyani/renkei/blob/main/docs/reference/config.en.md

`;
  return { text: header + quoteReferences(out), secrets };
}

/**
 * Replaces a value with the `${VAR}` of the variable that holds it, and returns
 * it unchanged when no variable does. Plain values (an issuer, a redirect URI)
 * are only referenced when they came from a variable verbatim, so the file
 * still reads as configuration rather than as a wall of indirection.
 * @param {Record<string, string>} env
 */
function referencer(env) {
  /** @type {Map<string, string>} */
  const byValue = new Map();
  for (const [name, value] of Object.entries(env)) {
    if (value && !byValue.has(value)) byValue.set(value, name);
  }
  /** @param {string | undefined} value */
  return (value) => {
    if (!value) return value;
    const name = byValue.get(value);
    return name ? `\${${name}}` : value;
  };
}
